"""Pemnambahan kolom total_discount dan total_price pada order table

Revision ID: 08fc1fe146fa
Revises: 
Create Date: 2022-10-27 19:45:04.014047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08fc1fe146fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('total_discount', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('total_price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'total_price')
    op.drop_column('order', 'total_discount')
    # ### end Alembic commands ###
