"""Create table apply loan

Revision ID: dd18afc6a5e5
Revises: 08fc1fe146fa
Create Date: 2022-10-30 15:03:31.872760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd18afc6a5e5'
down_revision = '08fc1fe146fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apply_loan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('sell_report_path', sa.String(length=100), nullable=True),
    sa.Column('finance_report_path', sa.String(length=100), nullable=True),
    sa.Column('account_statement_path', sa.String(length=100), nullable=True),
    sa.Column('sign_finance', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apply_loan')
    # ### end Alembic commands ###
